= AsciiReqs - Requirements Management using AsciiDoc markdown and git

== What it is

Requirement Management software is often complicated and inconvenient to use.
Support for collaboration and change management can be cumbersome and poor.
What if we could instead store our requirements in git and use that for versioning and use pull requests for review and management of changes?

This project is a (simple) parser for AsciiDoc files written in Python that will identify requirements in AsciiDoc files, and build a requirements project model from this.
It then uses this to do reporting and data export, and will also post process the AsciiDoc files to insert cross-links and report data.

The parser supports requirement document hierarchies, and can find and report inconsistencies in requirement cross-links between documents.

This allows complicated sets of product requirements to be written in AsciiDoc.

== Status

This is a prototype that I wrote out of frustration with an ancient and horrible (but common) Requirement Management System.  It was written to freshen up my Python skills.  It has some tests, but needs more and better error handling and more unit tests.

Still, it is in a workable state and the current functionality is at a level where it can be useful.

== Features

== How does it work?

