= User requirements for requirements management SW
:toc: macro
:toclevels: 4
:sectnums:
:sectnumlevels: 3
:disclosure: Internal
:req-children: req-tool-sw-reqs.adoc
:req-prefix: UR-RMS-REQ-

This is a page after the cover, where approval and history will go.

<<<

toc::[]

== Scope

This a sample requirement specification for testing of asciireqs, containing user requirements for a hypothetical Requirements Management System (termed "the SW" in this document).

== Context

== Functional requirements

=== Data management and collaboration

Reqirements are written as AsciiDoc "terms":

[[UR-RMS-REQ-011]]UR-RMS-REQ-011::
The SW shall support an internally hosted central data store.
+
Tags: Rel-1;
Child: xref:req-tool-sw-reqs.adoc#SW-RMS-REQ-011[SW-RMS-REQ-011]

[[UR-RMS-REQ-012]]UR-RMS-REQ-012::
The SW shall support versioning and baselining
+
Tags: Rel-2

[[UR-RMS-REQ-013]]UR-RMS-REQ-013::
The SW shall support review of changes and store the history of the review and approval process.
+
Tags: Rel-2

[[UR-RMS-REQ-014]]UR-RMS-REQ-014::
The SW shall support an efficient and smooth process for the proposal and approval of changes, to facilitate collaboration.
+
Tags: Rel-2

=== Hierarchical specifications

[[UR-RMS-REQ-021]]UR-RMS-REQ-021::
The SW shall support hierarchical specifications documents, and links between parent and child requirements.
+
Tags: Rel-1; Child: xref:req-tool-sw-reqs.adoc#SW-RMS-REQ-021[SW-RMS-REQ-021]


=== Reporting

[[UR-RMS-REQ-031]]UR-RMS-REQ-031::
The SW shall support exporting requirements tables to other formats
+
Tags: Rel-1; Child: xref:req-tool-sw-reqs.adoc#SW-RMS-REQ-031[SW-RMS-REQ-031]

[[UR-RMS-REQ-032]]UR-RMS-REQ-032::
The SW shall support analysis of requirements links between parent and child.
+
Tags: Rel-2;
Child: xref:req-tool-sw-reqs.adoc#SW-RMS-REQ-033[SW-RMS-REQ-033], xref:req-tool-sw-reqs.adoc#SW-RMS-REQ-034[SW-RMS-REQ-034], SW-RMS-RE-999

[[UR-RMS-REQ-033]]UR-RMS-REQ-033::
The SW shall be able to generate reports based on filters.
+
Tags: Rel-2;
Child: xref:req-tool-sw-reqs.adoc#SW-RMS-REQ-036[SW-RMS-REQ-036]

== Non functional requirements