= Software requirements for requirements management SW
:toc: macro
:toclevels: 4
:sectnums:
:sectnumlevels: 3
:disclosure: Internal
:req-prefix: SW-RMS-REQ-

This is a page after the cover, where approval and history will go.

<<<

toc::[]

== Scope

This a sample SW requirement specification for testing of asciireqs, containing user requirements for a hypothetical Requirements Management System (termed "the SW" in this document).

== Context

== Functional requirements

=== Data management and collaboration

[[SW-RMS-REQ-011]]SW-RMS-REQ-011::
The requirements shall be stored an asciidoc text files, for storage in a configuration management system like git.
+
Tags: Rel-1;
Parent: xref:req-tool-user-reqs.adoc#UR-RMS-REQ-011[UR-RMS-REQ-011], xref:req-tool-user-reqs.adoc#UR-RMS-REQ-012[UR-RMS-REQ-012], xref:req-tool-user-reqs.adoc#UR-RMS-REQ-013[UR-RMS-REQ-013], xref:req-tool-user-reqs.adoc#UR-RMS-REQ-014[UR-RMS-REQ-014]

=== Hierarchical specifications

[[SW-RMS-REQ-021]]SW-RMS-REQ-021:: An attribute for child documents shall be used to define the link between a parent and child specification document.
+
The attribute shall be on the form `:req-children: name.adoc`
+
Parent: xref:req-tool-user-reqs.adoc#UR-RMS-REQ-021[UR-RMS-REQ-021]; Tags: Rel-1

[[SW-RMS-REQ-022]]SW-RMS-REQ-022:: The SW shall insert AsciiDoc anchors for the requirement definition and cross-links where they are referenced
+
Parent: xref:req-tool-user-reqs.adoc#UR-RMS-REQ-021[UR-RMS-REQ-021]; Tags: Rel-1

=== Reporting

[[SW-RMS-REQ-031]]SW-RMS-REQ-031::
The SW shall support exporting the requirements from a document to CVS format.
+
Tags: Rel-1;
Parent: xref:req-tool-user-reqs.adoc#UR-RMS-REQ-031[UR-RMS-REQ-031]

[[SW-RMS-REQ-032]]SW-RMS-REQ-032::
The SW shall generate reports using asciidoc template files with macros that define the location and type of report elements to insert.
+
Tags: Rel-2

[[SW-RMS-REQ-033]]SW-RMS-REQ-033::
The SW shall be able to generate a report table that lists requirements that lack parents.
+
Tags: Rel-2;
Parent: xref:req-tool-user-reqs.adoc#UR-RMS-REQ-032[UR-RMS-REQ-032]

[[SW-RMS-REQ-034]]SW-RMS-REQ-034::
The SW shall be able to generate a report table that lists requirements that lack children.
+
Tags: Rel-2;
Parent: xref:req-tool-user-reqs.adoc#UR-RMS-REQ-032[UR-RMS-REQ-032]

[[SW-RMS-REQ-035]]SW-RMS-REQ-035::
The SW shall be able to generate a report table that lists requirements that have inconsistent parent/child relationships (linked in only one direction).
+
Tags: Rel-2;
Parent: xref:req-tool-user-reqs.adoc#UR-RMS-REQ-032[UR-RMS-REQ-032]

[[SW-RMS-REQ-036]]SW-RMS-REQ-036::
The SW shall be able to generate reports based on general requirement attribute filters.
+
Tags: Rel-2;
Parent: xref:req-tool-user-reqs.adoc#UR-RMS-REQ-033[UR-RMS-REQ-033]

== Non functional requirements

== Requirements for release 1

|===
|ID |Text |Tags 

|xref:req-tool-sw-reqs.adoc#SW-RMS-REQ-011[SW-RMS-REQ-011]
|The requirements shall be stored an asciidoc text files, for storage in a configuration management system like git.

|Rel-1

|xref:req-tool-sw-reqs.adoc#SW-RMS-REQ-021[SW-RMS-REQ-021]
|An attribute for child documents shall be used to define the link between a parent and child specification document.

The attribute shall be on the form `:req-children: name.adoc`
|Rel-1

|xref:req-tool-sw-reqs.adoc#SW-RMS-REQ-022[SW-RMS-REQ-022]
|The SW shall insert AsciiDoc anchors for the requirement definition and cross-links where they are referenced
|Rel-1

|xref:req-tool-sw-reqs.adoc#SW-RMS-REQ-031[SW-RMS-REQ-031]
|The SW shall support exporting the requirements from a document to CVS format.

|Rel-1

|===
